### ISSUE TITLE
small difference

### ISSUE THREAD

**Issue by eried** [shaggyone/multiboard-parametric#1]
hi! awesome generator, do you think on adding more features like "hole generation" or such to make custom shapes?

I generated a tile vs the original stl and the only difference were the small threads, diff between the 2 stls was this:

![image](https://github.com/shaggyone/multiboard-parametric/assets/1091420/418c5ae6-374c-4d22-9fc9-6b6310721a0d)

**Comment by shaggyone** [comment]
@eried could you provide the diff's stl somehow?

**Comment by eried** [comment]
hi, oh I dont have them anymore, but now after more days of experience I am just thinking it is the orientation of the threads
